### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by fungs** [SIBCI/rfc#11]
The current draft states for file listings such as CONT_FASTQ_FILE_LISTING that the paths must be absolute. However, the caller from outside the container would have less work if the paths could be relative to the location of the listing file. He/she could simple drop the files next to the list and make the location available to the container. This would still allow for absolute paths (beginning with /) although I would always prefer to not create files with container-specific content.

**Comment by pbelmann** [comment]
I think he provided this #31 branch but he accidentally closed it.

**Comment by michaelbarton** [comment]
Implemented in #31
